"""
REALM FORGE: MISSION SCHEMAS v1.0
PURPOSE: Defines the data structures for mission requests, strategies, and responses.
PATH: F:/agentic_workforce/src/api/schemas/mission_schema.py
"""

from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class MissionRequest(BaseModel):
    """The incoming request from the UI."""
    task: str = Field(..., example="Analyze the current cybersecurity logs and fix vulnerabilities.")
    priority: Optional[str] = "MEDIUM"
    metadata: Optional[Dict[str, Any]] = {}

class MissionStep(BaseModel):
    """A single step in a multi-agent strike strategy."""
    step: int
    silo: str
    action: str

class MissionStrategy(BaseModel):
    """The full plan generated by the Orchestrator."""
    mission_title: str
    required_silos: List[str]
    steps: List[MissionStep]

class MissionResponse(BaseModel):
    """The standardized success response."""
    status: str = "SUCCESS"
    mission_id: str
    strategy: Optional[MissionStrategy] = None